---
title: OpenActive
timezone: UTC
collections:
  booking_engines:
    title: Booking Systems
    output: true
  case_studies:
    title: Case Studies
    output: true
  dataproviders:
    title: Data Providers
    output: true
  events:
    title: Events
    output: true
  faqs:
    title: FAQs
    output: true
  members:
    title: Members
    output: true
  mentors:
    title: Mentors
    output: true
  partners:
    title: Partners
    output: true
  posts:
    title: Posts
    output: true
  champions:
    title: Champions
    output: true
  uploads:
    title: Uploads
    output: true
    permalink: "/uploads/:path/"
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
    is_main_navigation: false
    is_secondary_navigation: false
- scope:
    path: ''
    type: posts
  values:
    layout: post
    is_featured: false
    thumbnail_image: ''
    categories: About OpenActive
- scope:
    path: ''
    type: case_studies
  values:
    layout: case-study
    is_featured: false
    thumbnail_image: "/uploads/placeholder.png"
    member: 
    strapline: 
- scope:
    path: ''
    type: mentors
  values:
    layout: mentor
    is_featured: false
    thumbnail_image: "/uploads/placeholder.png"
    twitter: 
    linkedin: 
    role: 
- scope:
    path: ''
    type: partners
  values:
    layout: partner
    is_featured: false
    thumbnail_image: "/uploads/placeholder.png"
- scope:
    path: ''
    type: dataproviders
  values:
    layout: dataprovider
    is_featured: false
    thumbnail_image: "/uploads/placeholder.png"
- scope:
    path: ''
    type: members
  values:
    layout: member
    is_featured: false
    thumbnail_image: "/uploads/placeholder.png"
    website: Web address
- scope:
    path: ''
    type: booking_engines
  values:
    layout: booking-engine
    is_featured: false
    is_enabled: false
    thumbnail_image: "/uploads/placeholder.png"
    member: 
    website: Web address
- scope:
    path: ''
    type: champions
  values:
    thumbnail_image: "/uploads/placeholder.png"
    role:
    company:
    link:
    linkedin:
permalink: pretty
