---
title: OpenActive
timezone: UTC
collections:
  booking_engines:
    title: Booking Engines
    output: true
    member: ''
  case_studies:
    title: Case Studies
    output: true
  events:
    title: Events
    output: true
  faqs:
    title: FAQs
    output: true
  members:
    title: Members
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
    is_main_navigation: false
    is_secondary_navigation: false
- scope:
    path: ''
    type: posts
  values:
    layout: post
    is_featured: false
    thumbnail_image: ''
- scope:
    path: ''
    type: case_studies
  values:
    layout: case-study
    is_featured: false
    thumbnail_image: "/uploads/placeholder.png"
    facts_figures: 3 -5 facts and figures
    the_challenge_text: Explain the challenge you faced
    solving_the_problem_text: How did you solve the problem
    the_impact_text: What was the impact?
    lessons_learned_text: What lessons were learned?
- scope:
    path: ''
    type: members
  values:
    layout: member
    is_featured: false
    thumbnail_image: "/uploads/placeholder.png"
    website: Web address
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

locale: en-US
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: "/openactive"
url: https://github.com/imaginatecreative
repository: imaginatecreative/openactive
email: your-email@example.com
github_username: imaginatecreative
twitter_username: twitter
youtube_username: 
facebook_username: 
instagram_username: 
pinterest_username: 
medium_username: medium
markdown: kramdown
plugins:
- jekyll-feed
staticman:
  branch: master
reCaptcha:
  siteKey: sitekey
  secret: 
atom_feed:
  path: 
search: 
search_full_content: 
tipue_search:
  include:
    pages: true
