---
title: OpenActive
timezone: UTC
collections:
  case_studies:
    title: Case Studies
    output: true
  events:
    title: Events
    output: true
  faqs:
    title: FAQs
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
    is_main_navigation: false
    is_secondary_navigation: false
locale: en-US
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: "/openactive"
url: https://github.com/imaginatecreative/openactive
repository: imaginatecreative/openactive
email: your-email@example.com
github_username: imaginatecreative
twitter_username: twitter
youtube_username: 
facebook_username: 
instagram_username: 
pinterest_username: 
medium_username: medium
markdown: kramdown
plugins:
- jekyll-feed
staticman:
  branch: master
reCaptcha:
  siteKey: sitekey
  secret: 
atom_feed:
  path: 
search: 
search_full_content: 


