---
title: OpenActive
timezone: UTC
collections:
  events:
    title: Events
    output: true
  posts:
    title: Posts
    output: true
  faqs:
    title: FAQs
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
    is_main_navigation: false
    is_secondary_navigation: false
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: "/openactive"
url: 'https://github.com/imaginatecreative/openactive'
twitter_username: twitter
youtube_username:
facebook_username:
instagram_username:
pinterest_username:
medium_username: medium
markdown: kramdown
plugins:
- jekyll-feed
